<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ReportCleaningBathroomModel extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
   
    
    /*
     * Get all SPL count report
     */
    function getAllReportingCount(){
       // ini_set('memory_limit', '-1');
       $data =   $this->session->all_userdata();
       $username = $data['nik'];  

        $sql = " SELECT dt_buildings.BUILDINGS_ID ,dt_areas.NAME, dt_buildings.TANGGAL, dt_buildings.TIME,
        dt_buildings.LANTAI, dt_buildings.SARANG_LABA_LABA, dt_buildings.KACA, dt_buildings.BESI_UWF,
        dt_buildings.TEMPAT_SAMPAH, dt_buildings.CATATAN, dt_buildings.CREATED_BY, dt_buildings.CREATED_DATE
        FROM dt_buildings JOIN dt_areas ON dt_buildings.AREA_ID = dt_areas.AREA_ID ";

        $query = $this->db->query($sql);

        return $query->num_rows();
    }
        
    /*
     * Get all SPL report
     */
    function getAllDataCleaning ( $params = array() ){
       // ini_set('memory_limit', '-1');
        $this->load->library('session');
        $data =   $this->session->all_userdata();
        $username = $data['nik'];  


        if(isset($params) && !empty($params)){
            $this->db->limit($params['limit'], $params['offset']);
        }
        
        $sql = " SELECT dt_buildings.BUILDINGS_ID ,dt_areas.NAME, dt_buildings.TANGGAL, dt_buildings.TIME,
        dt_buildings.LANTAI, dt_buildings.SARANG_LABA_LABA, dt_buildings.KACA, dt_buildings.BESI_UWF,
        dt_buildings.TEMPAT_SAMPAH, dt_buildings.CATATAN, dt_buildings.CREATED_BY, dt_buildings.CREATED_DATE
        FROM dt_buildings JOIN dt_areas ON dt_buildings.AREA_ID = dt_areas.AREA_ID
        ORDER BY dt_buildings.CREATED_DATE DESC ";

        $query = $this->db->query($sql);

        return $query->result_array();

    }

     /*
     * Get search  SPL count report
     */
    function getSearchAllSPLcount( $startDate, $endDate, $areaId ){
        // ini_set('memory_limit', '-1');
        $data =   $this->session->all_userdata();
        $username = $data['nik'];  

        $sql = " SELECT dt_buildings.BUILDINGS_ID , dt_areas.AREA_ID,dt_areas.NAME,dt_areas.TYPE, 
        dt_buildings.TANGGAL, dt_buildings.TIME, dt_buildings.LANTAI, dt_buildings.SARANG_LABA_LABA, 
        dt_buildings.KACA, dt_buildings.BESI_UWF,dt_buildings.TEMPAT_SAMPAH, dt_buildings.CATATAN,
        dt_buildings.CREATED_BY, dt_buildings.CREATED_DATE 
        FROM dt_buildings JOIN dt_areas ON dt_buildings.AREA_ID = dt_areas.AREA_ID
        WHERE dt_areas.AREA_ID='$areaId' 
        AND dt_buildings.TANGGAL BETWEEN '$startDate' AND '$endDate'
        ORDER BY dt_buildings.CREATED_DATE DESC ";

        $query = $this->db->query($sql);

        return $query->num_rows();
     }

    /*
     * Get search SPL report
     */
    function getSearchAllSPL( $params = array(), $startDate, $endDate, $areaId ){
   
        $this->load->library('session');
 
        $data =   $this->session->all_userdata();
        $username = $data['nik'];  
 
        if(isset($params) && !empty($params)){
            $this->db->limit($params['limit'], $params['offset']);
       }
        
       $sql = " SELECT dt_buildings.BUILDINGS_ID , dt_areas.AREA_ID,dt_areas.NAME,dt_areas.TYPE, 
        dt_buildings.TANGGAL, dt_buildings.TIME, dt_buildings.LANTAI, dt_buildings.SARANG_LABA_LABA, 
        dt_buildings.KACA, dt_buildings.BESI_UWF,dt_buildings.TEMPAT_SAMPAH, dt_buildings.CATATAN,
        dt_buildings.CREATED_BY, dt_buildings.CREATED_DATE 
        FROM dt_buildings JOIN dt_areas ON dt_buildings.AREA_ID = dt_areas.AREA_ID
        WHERE dt_areas.AREA_ID='$areaId' 
        AND dt_buildings.TANGGAL BETWEEN '$startDate' AND '$endDate'
        ORDER BY dt_buildings.CREATED_DATE DESC ";

        $query = $this->db->query($sql);

        return $query->result_array();
    }
         
}