<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_bathrooms extends MX_Controller{
    function __construct()
    {
        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->model('UserBathroomModel');
    } 

    /*
     * warehouse
     */
    function index(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }

        $data = array();
        
        $data['content'] = $this->load->view('user_bathrooms/index',$data,true);

        $this->parser->parse(TEMPLATE.'/content', $data);
    }
    

     /*
     * Adding a new report bathrooms
     */
    function add()
    {   
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('form_validation');

		$this->form_validation->set_rules('notes','Notes','required|max_length[500]');
		
      

		if($this->form_validation->run())     
        {

        $params = array(
            'AREA_ID' => $this->input->post('areaName'),
            'TANGGAL'=> $this->input->post('dateCleaning'),
            'TIME'=> $this->input->post("timeCleaning"),
            'TOILET'=> strval($this->input->post("closet")),
            'SABUN'=> strval($this->input->post("soap")),
            'LANTAI'=> strval($this->input->post("floor")),
            'DINDING'=> strval($this->input->post("wall")),
            'AROMA'=> strval($this->input->post("scent")),
            'KAIN'=> strval($this->input->post("towel")),
            'PINTU'=> strval($this->input->post("door")),
            'KRAN'=> strval($this->input->post("faucet")),
            'TEMPAT_SAMPAH'=> strval($this->input->post("trash")),
            'CATATAN'=> strval($this->input->post("notes")),
            'CREATED_BY'=> $this->input->post("createdByHide"),
            'CREATED_DATE' => date("Y-m-d H:i:s")
        );

            $user_id = $this->UserBathroomModel->add_dt_bathrooms( $params ); 
            $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Data Saved!<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
            redirect('index.php/user/bathroom');
        }
        else
        { 

        $data['content'] = $this->load->view('user_bathrooms/index', null, true);
        $this->parser->parse(TEMPLATE.'/content', $data);
        }
    }  


    /*
     * Search Karyawan
     */
    function set_search() {
        $keyword = $this->input->post('keyword');
        $this->session->set_userdata('kom_sess_keyword',$keyword);
        redirect('index.php/administrator/komentar');
    }

    /*
     * Create SPL
     */
    function CreateSPL(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
       // $params['limit'] = RECORDS_PER_PAGE; 
       // $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
       // $config = $this->config->item('pagination');
       // $config['base_url'] = site_url('index.php/user_employee/index');
       // $config['total_rows'] = $this->Employee_model->get_all_komentar_count();
       // $this->pagination->initialize($config);

        //$data['publikasi'] = $this->Employee_model->get_all_komentar($params);
        $data['publikasi'] = $this->Employee_model->get_all_komentar();
        
        $data['content'] = $this->load->view('user_employee/CreateSPL',$data,true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }


    function createNewSPL(){
       
       print_r("controller OK");
       // $endTime = $_POST['endTime'];
  

       $isActive = 'T';
       $otCompId = 1;

       $params = array(
        'SPLID' => $_POST['splId'],
        'RefNo' => $_POST['reffNo'],
        'Periode'=>  $_POST['datePeriode'],
        'SPLDesc'=>  $_POST['splDesc'],
        'VOT'=> $_POST['time'],
        'BREAK'=>  $_POST['breaks'],
        'StyleNo'=> $_POST['styleNo'],
        'OT'=>  $_POST['startTime'],
        'OTH'=> $_POST['endTime'],
        'TOTOT'=> $_POST['totOT'],
        'IsActive'=> $isActive,
        'OTCompID'=>$otCompId,
        'created_by'=> $_POST['createdBy']
    );
  
    $splId = $this->Employee_model->add_SPL($params); 
     //  print_r($splId);
     //  print_r($styleNo);
    
    }

    function createNewDetailSPL(){
       
        print_r("controller detail");
        // print_r($_POST['splId']);
        // die();
        // splId: splId, 
        // groupId: groupId,
        // employeeId: employeeId

        $params = array(
            'SPLID' => $_POST['splId'],
            'GroupID' => $_POST['groupId'],
            'EmployeeID'=>  $_POST['employeeId']
        );
   
       $splId = $this->Employee_model->add_Detail_SPL($params); 
     
     }

     function ListSPL(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
       $params['limit'] = RECORDS_PER_PAGE; 
       $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
       $config = $this->config->item('pagination');
       $config['base_url'] = site_url('index.php/user_employee/ListSPL');
       $config['total_rows'] = $this->Employee_model->get_all_spl_count();
       $this->pagination->initialize($config);

        $data['splid'] = $this->Employee_model->get_all_spl($params);
        $data['groupIds'] = $this->Employee_model->get_group_desc($params);
        
        $data['content'] = $this->load->view('user_employee/ListSPL',$data,true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }

    /*
     * Editing SPL
     */
    function edit($id)
    {   
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        // check if the user exists before trying to edit it
         $data['spl'] = $this->Employee_model->get_spl($id);
         $data['splEmployee'] = $this->Employee_model->getEmployeeSPL($id);


        if(isset($data['spl']['SPLID']))
        {
                $data['content'] = $this->load->view('user_employee/edit',$data,true);
                $this->parser->parse(TEMPLATE.'/content', $data);
        }
        else
        show_error('The user you are trying to edit does not exist.');
    } 

    function DataEditSPL(){
           print_r("controller");
           // $endTime = $_POST['endTime'];
    
           $isActive = 'T';
           $otCompId = 1;
    
           $params = array(
            'RefNo' => $_POST['reffNo'],
            'Periode'=>  $_POST['datePeriode'],
            'SPLDesc'=>  $_POST['splDesc'],
            'VOT'=> $_POST['time'],
            'BREAK'=>  $_POST['breaks'],
            'StyleNo'=> $_POST['styleNo'],
            'OT'=>  $_POST['startTime'],
            'OTH'=> $_POST['endTime'],
            'TOTOT'=> $_POST['totOT'],
            'IsActive'=> $isActive,
            'OTCompID'=>$otCompId,
            'created_by'=> $_POST['createdBy']
        );
        $id = $_POST['splId'];
  
        $this->Employee_model->update_spl($id,$params);
    }

    /*
     * Deleting employee and SPLID
     */
    function remove($splid, $employeeId)
    {
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
       
        $user = $this->Employee_model->getSPLDetail($splid, $employeeId);
       // check if the user exists before trying to delete it
        if(isset($user['SPLID']) && isset($user['EmployeeID']))
        {
            $this->Employee_model->deleteEmployeSPLID($splid, $employeeId);
            $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Deleted Employee Succes !<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
            redirect('index.php/user/employee/edit/'.$splid);
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }

}
