<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Menu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by id
     */
    function get_menu($id)
    {
        return $this->db->get_where('g_menus',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all menu count
     */
    function get_all_menu_count()
    {
        $this->db->from('g_menus');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all menu
     */
    function get_all_menu($params = array())
    {
        $this->db->order_by('ordering', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('g_users b','a.created_by=b.U_ID');
        return $this->db->get('g_menus a')->result_array();
    }
        
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('g_menus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('menu',$params);
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($id)
    {
        return $this->db->delete('g_menus',array('id'=>$id));
    }
}
