<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_employee extends MX_Controller{
    function __construct()
    {
        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->model('Employee_model');
    } 

    /*
     * Listing of publikasi
     */
    function index(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('index.php/admin_employee/index');
        $config['total_rows'] = $this->Employee_model->get_all_komentar_count();
        $this->pagination->initialize($config);

        $data['publikasi'] = $this->Employee_model->get_all_komentar($params);
        
        $data['content'] = $this->load->view('admin_employee/index',$data,true);
        $this->parser->parse(TEMPLATE.'/content_admin', $data);
    }
    
    function set_search() {
        $keyword = $this->input->post('keyword');
        $this->session->set_userdata('kom_sess_keyword',$keyword);
        redirect('administrator/komentar');
    }

    function toExcel(){
         $params['limit'] = RECORDS_PER_PAGE; 
         $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
         $data['publikasi'] = $this->Komentar_model->get_all_komentar($params);
         $data['content']   = $this->load->view('admin_komentar/save',$data,true);
         $this->load->view('admin_komentar/save');
   }

   function export_xls() {

        $this->load->library('excel');
        
        $objset = $this->excel->setActiveSheetIndex(0);
        $this->excel->getActiveSheet()->setTitle('File Komentar');
        
        //judul kolom excel
        create_excel_row($this->excel,'A1','Pengirim','bold');
        create_excel_row($this->excel,'B1','Email','bold');
        create_excel_row($this->excel,'C1','Pertanyaan','bold');
        create_excel_row($this->excel,'D1','Nilai','bold');
        create_excel_row($this->excel,'E1','komentar','bold');
        create_excel_row($this->excel,'F1','Created Date','bold');
        
        
        //Setting lebar cell
        $this->excel->getActiveSheet()->getColumnDimension('A')->setWidth(25); //pengirim
        $this->excel->getActiveSheet()->getColumnDimension('B')->setWidth(25); //email
        $this->excel->getActiveSheet()->getColumnDimension('C')->setWidth(30); //pertanyaan
        $this->excel->getActiveSheet()->getColumnDimension('D')->setWidth(10); //nilai
        $this->excel->getActiveSheet()->getColumnDimension('E')->setWidth(25); //komentar
        $this->excel->getActiveSheet()->getColumnDimension('F')->setWidth(22); //created date

        //ambil data masukkan ke baris
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        $a = $this->Komentar_model->get_all_komentar($params);

        //ambil masukan ke kolom excel
        $baris  = 2;
            foreach ($a as $c){ 

                $per = str_replace(",","\n",$c['pertanyaan'],$i);
                $nil = str_replace(",","\n",$c['nilai'],$i);

                $objset->setCellValue("A".$baris, $c['pengirim']); 
                $objset->setCellValue("B".$baris, $c['email']); 
                $objset->setCellValue("C".$baris, $per); 
                $objset->setCellValue("D".$baris, $nil); 
                $objset->setCellValue("E".$baris, $c['komentar']); 
                $objset->setCellValue("F".$baris, $c['created_date']); 
                $baris++;
            }


        /** Borders for all data */
        $styleArray = array(
            'borders' => array(
                'allborders' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN,
                ),
            )
        );

        //set row pertanyaan dan nilai
        $bar = 2;
        $bar2 = 3;
            foreach ($a as $b) {
                # code...
                $this->excel->getActiveSheet()->getStyle("C".$bar.":"."C".$bar2)
                            ->getAlignment()->setWrapText(true);

                $this->excel->getActiveSheet()->getStyle("D".$bar.":"."D".$bar2)
                            ->getAlignment()->setWrapText(true);     
                $bar++;
                $bar2++;
            }


        //format style excel
        $this->excel->getActiveSheet()->getStyle('A2')
                    ->getAlignment()->applyFromArray(
                        array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,));

        $this->excel->getActiveSheet()->getStyle('A1:F1')
                    ->applyFromArray($styleArray);
            
        $this->excel->getActiveSheet()->getStyle('A1:F1'.$this->excel->getActiveSheet()->getHighestRow())
                    ->applyFromArray($styleArray);
        
        header('Content-Type: application/vnd.ms-excel'); //mime type
        header('Content-Disposition: attachment;filename="File Komentar.xls"'); 
        header('Cache-Control: max-age=0'); //no cache
        $objWriter = PHPExcel_IOFactory::createWriter($this->excel, 'Excel5');  
        $objWriter->save('php://output');
    }
}
