<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ReportSPLModelAdmin extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
   
    
    /*
     * Get all SPL count report
     */
    function getAllSPLcount(){
       // ini_set('memory_limit', '-1');
       $data =   $this->session->all_userdata();
       $username = $data['nik'];  

       $this->db->select('*');

        $keyword = $this->session->userdata('kom_sess_keyword');
        if ($keyword != "") {
            $this->db->like('k.pengirim',$keyword);
            $this->db->or_like('k.komentar',$keyword);
        }
        $this->db->from('v_report_spl');
        
        return $this->db->count_all_results();
    }
        
    /*
     * Get all SPL report
     */
    function getAllSPL( $params = array() ){
       // ini_set('memory_limit', '-1');
        $this->load->library('session');
        $data =   $this->session->all_userdata();

        $this->db->select('*');
        $this->db->order_by('periode', 'desc');

        if(isset($params) && !empty($params)){
            $this->db->limit($params['limit'], $params['offset']);
        }
        
        return $this->db->get('v_report_spl')->result_array();
    }

     /*
     * Get search  SPL count report
     */
    function getSearchAllSPLcount( $startDate, $endDate ){
        // ini_set('memory_limit', '-1');
        $data =   $this->session->all_userdata();

        $this->db->select('*');
        $this->db->where('periode >=', $startDate);
        $this->db->where('periode <=', $endDate);


        $this->db->from('v_report_spl');
        return $this->db->count_all_results();
     }

    /*
     * Get search SPL report
     */
    function getSearchAllSPL( $params = array(), $startDate, $endDate ){
   
         $this->load->library('session');
 
         $data =   $this->session->all_userdata();

         $this->db->select('*');
         $this->db->where('periode >=', $startDate);
         $this->db->where('periode <=', $endDate);
 
         if(isset($params) && !empty($params)){
             $this->db->limit($params['limit'], $params['offset']);
         }
         
        return $this->db->get('v_report_spl')->result_array();
    }
         
}