<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_employee extends MX_Controller{
    function __construct()
    {
        parent::__construct();
        $this->sess_id = $this->session->userdata('userid');
        $this->load->model('Employee_model');
    } 

    /*
     * Listing of publikasi
     */
    function index(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('index.php/user_employee/CreateSPL');
        $config['total_rows'] = $this->Employee_model->get_all_komentar_count();
        $this->pagination->initialize($config);

        $data['publikasi'] = $this->Employee_model->get_all_komentar($params);
        
        $data['content'] = $this->load->view('user_employee/CreateSPL',$data,true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }
    
    /*
     * Search Karyawan
     */
    function set_search() {
        $keyword = $this->input->post('keyword');
        $this->session->set_userdata('kom_sess_keyword',$keyword);
        redirect('index.php/administrator/komentar');
    }

    /*
     * Create SPL
     */
    function CreateSPL(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
       // $params['limit'] = RECORDS_PER_PAGE; 
       // $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
       // $config = $this->config->item('pagination');
       // $config['base_url'] = site_url('index.php/user_employee/index');
       // $config['total_rows'] = $this->Employee_model->get_all_komentar_count();
       // $this->pagination->initialize($config);

        //$data['publikasi'] = $this->Employee_model->get_all_komentar($params);
        $data['publikasi'] = $this->Employee_model->get_all_komentar();
        
        $data['content'] = $this->load->view('user_employee/CreateSPL',$data,true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }

    /*
     * Adding a new record SPL
     */
    function add()
    {   
        // if(empty($this->sess_id)) {
        //     redirect('administrator/login');
        // }
        
        $this->load->library('form_validation');
        $data = $this->input->post('username');
        // print_r("data",$data); 
        // new record emp0011
        // $startTime = $this->input->post('startTime');
        // $endTime = $this->input->post('endTime');
        // $break = $this->input->post('break');
        $isActive = 'T';
        $otCompId = 1;
        $startTime = $this->input->post('startTime');
        $endTime = $this->input->post('endTime');
        //print_r("startTime ".$startTime);
        //print_r("endTime ".$endTime);
        // format ot oth totot
        //print_r("startTime",$startTime);
        //print_r("Break",$break);
        //die();

        $params = array(
            'SPLID' => $this->input->post('splId'),
            'RefNo' => $this->input->post('reffNo'),
            'Periode'=> $this->input->post('datePeriode'),
            'SPLDesc'=> $this->input->post('splDesc'),
            'VOT'=> $this->input->post('time'),
            'BREAK'=> $this->input->post('break'),
            'StyleNo'=> $this->input->post('styleNo'),
            'OT'=> $startTime,
            'OTH'=> $endTime,
            'TOTOT'=> $startTime,
            'IsActive'=> $isActive,
            'OTCompID'=>$otCompId
        );
         // print_r($params);
         // die();
        $splId = $this->Employee_model->add_SPL($params); 
         // die();

	//	 if($this->form_validation->run())     
        // {
        //     // new record emp0011
        //     $startTime = $this->input->post('startTime');
        //     $endTime = $this->input->post('endTime');
        //     $isActive = 'T';
        //     $otCompId = 1;
        //     // format ot oth totot

        //     $params = array(
        //         'SPLID' => $this->input->post('splId'),
        //         'RefNo' => $this->input->post('reffNo'),
        //         'Periode'=> $this->input->post('datePeriode'),
        //         'SPLDesc'=> $this->input->post('splDesc'),
        //         'VOT'=> $this->input->post('time'),
        //         'BREAK'=> $this->input->post('break'),
        //         'StyleNo'=> $this->db->post('styleNo'),
        //         'OT'=> $ot,
        //         'OTH'=> $oth,
        //         'TOTOT'=> $totot,
        //         'IsActive'=> $isActive,
        //         'OTCompID'=>$otCompId
        //     );
        //     print_r($param);
        
     //     $splId = $this->Employee_model->add_SPL($params); 
        //  //   die();
        //     // new record emp0012
        //     $params = array(
        //         'SPLID' => $this->input->post('splId'),
        //         'GroupID' => $this->input->post('groupId'),
        //         'EmployeeID'=> $this->input->post('employeeId')
        //     );
        //     $detailSPLId = $this->Employee_model->add_detail_SPL($params); 

           // $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Data Tersimpan<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
         //   redirect('/index.php/user/employee');
      //  }
       // else
       // { 
         //   $data['content'] = $this->load->view('user_employee/CreateSPL',null,true);
           // $this->parser->parse(TEMPLATE.'/content', $data);
       //    redirect('/index.php/user/employee');
       // }
    }  

    function createNewSPL(){
       
       print_r("controller OK");
       // $endTime = $_POST['endTime'];
  

       $isActive = 'T';
       $otCompId = 1;

       $params = array(
        'SPLID' => $_POST['splId'],
        'RefNo' => $_POST['reffNo'],
        'Periode'=>  $_POST['datePeriode'],
        'SPLDesc'=>  $_POST['splDesc'],
        'VOT'=> $_POST['time'],
        'BREAK'=>  $_POST['breaks'],
        'StyleNo'=> $_POST['styleNo'],
        'OT'=>  $_POST['startTime'],
        'OTH'=> $_POST['endTime'],
        'TOTOT'=> $_POST['totOT'],
        'IsActive'=> $isActive,
        'OTCompID'=>$otCompId,
        'created_by'=> $_POST['createdBy']
    );
  
    $splId = $this->Employee_model->add_SPL($params); 
     //  print_r($splId);
     //  print_r($styleNo);
    
    }

    function createNewDetailSPL(){
       
        print_r("controller detail");
        // print_r($_POST['splId']);
        // die();
        // splId: splId, 
        // groupId: groupId,
        // employeeId: employeeId

        $params = array(
            'SPLID' => $_POST['splId'],
            'GroupID' => $_POST['groupId'],
            'EmployeeID'=>  $_POST['employeeId']
        );
   
       $splId = $this->Employee_model->add_Detail_SPL($params); 
     
     }

     function ListSPL(){
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        $this->load->library('pagination');
        
       $params['limit'] = RECORDS_PER_PAGE; 
       $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
       $config = $this->config->item('pagination');
       $config['base_url'] = site_url('index.php/user_employee/ListSPL');
       $config['total_rows'] = $this->Employee_model->get_all_spl_count();
       $this->pagination->initialize($config);

        $data['splid'] = $this->Employee_model->get_all_spl($params);
        $data['groupIds'] = $this->Employee_model->get_group_desc($params);
        
        $data['content'] = $this->load->view('user_employee/ListSPL',$data,true);
        $this->parser->parse(TEMPLATE.'/content', $data);
    }

    /*
     * Editing SPL
     */
    function edit($id)
    {   
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
        
        // check if the user exists before trying to edit it
         $data['spl'] = $this->Employee_model->get_spl($id);
         $data['splEmployee'] = $this->Employee_model->getEmployeeSPL($id);


        if(isset($data['spl']['SPLID']))
        {
                $data['content'] = $this->load->view('user_employee/edit',$data,true);
                $this->parser->parse(TEMPLATE.'/content', $data);
        }
        else
        show_error('The user you are trying to edit does not exist.');
    } 

    function DataEditSPL(){
           print_r("controller");
           // $endTime = $_POST['endTime'];
    
           $isActive = 'T';
           $otCompId = 1;
    
           $params = array(
            'RefNo' => $_POST['reffNo'],
            'Periode'=>  $_POST['datePeriode'],
            'SPLDesc'=>  $_POST['splDesc'],
            'VOT'=> $_POST['time'],
            'BREAK'=>  $_POST['breaks'],
            'StyleNo'=> $_POST['styleNo'],
            'OT'=>  $_POST['startTime'],
            'OTH'=> $_POST['endTime'],
            'TOTOT'=> $_POST['totOT'],
            'IsActive'=> $isActive,
            'OTCompID'=>$otCompId,
            'created_by'=> $_POST['createdBy']
        );
        $id = $_POST['splId'];
  
        $this->Employee_model->update_spl($id,$params);
    }

    /*
     * Deleting employee and SPLID
     */
    function remove($splid, $employeeId)
    {
        if(empty($this->sess_id)) {
            redirect('index.php/administrator/login');
        }
       
        $user = $this->Employee_model->getSPLDetail($splid, $employeeId);
       // check if the user exists before trying to delete it
        if(isset($user['SPLID']) && isset($user['EmployeeID']))
        {
            $this->Employee_model->deleteEmployeSPLID($splid, $employeeId);
            $this->session->set_flashdata('msg','<div class="alert alert-warning alert-dismissible fade show" role="alert">Deleted Employee Succes !<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>');
            redirect('index.php/user/employee/edit/'.$splid);
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }

}
